#!/usr/bin/python3
Traceback NameError \n
